#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

source ops/ci/lib.sh

cleanup() {
  rm -f agent/repo-score.json agent/repo-score.md
}
trap cleanup EXIT

rewrite_with_header() {
  local header_file="$1"
  local target_file="$2"
  local tmp
  tmp="$(mktemp)"
  {
    cat "$header_file"
    tail -n +1 "$target_file"
  } >"$tmp"
  mv "$tmp" "$target_file"
}

# Refresh the committed README badge artifacts from the public score report.
jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history

json_header="$(mktemp)"
svg_header="$(mktemp)"
cat >"$json_header" <<'EOF'
// Generated by: jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history
// Source: agent/badge.toml
// Regenerate: `bash ops/ci/jankurai-badge.sh`
// DO NOT EDIT BY HAND.
EOF
cat >"$svg_header" <<'EOF'
<!-- Generated by: jankurai audit . --mode ratchet --full --baseline agent/baselines/main.repo-score.json --json agent/repo-score.json --md agent/repo-score.md --no-score-history -->
<!-- Source: agent/badge.toml -->
<!-- Regenerate: `bash ops/ci/jankurai-badge.sh` -->
<!-- DO NOT EDIT BY HAND. -->
EOF
rewrite_with_header "$json_header" agent/jankurai-badge.json
rewrite_with_header "$svg_header" agent/jankurai-badge.svg
rm -f "$json_header" "$svg_header"

test -s agent/jankurai-badge.svg
test -s agent/jankurai-badge.json
git diff --exit-code -- README.md agent/jankurai-badge.svg agent/jankurai-badge.json
