/// Discriminant for what the runtime should do when a command fires.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SlashAction {
    Help,
    Quit,
    NewSession,
    Clear,
    Echo,
    Panels,
    Compact,
    Model,
    Config,
    Mcp,
    Resume,
    Permissions,
    Status,
    Cost,
    Init,
    Review,
    Login,
    Logout,
    Agents,
    Memory,
    Copy,
    Export,
    Ps,
    Stop,
    Cd,
    Theme,
    Doctor,
    Bug,
    Rename,
    AddDir,
    Vim,
    Jankurai,
    Audit,
    AuditCheck,
    JankuraiStatus,
    Score,
    Sandbox,
    Keys,
    Daemon,
    Plugin,
    Features,
    Session,
    Fork,
    Attach,
    Serve,
    Run,
    Completion,
    Providers,
    Models,
    Acp,
    McpServer,
    Debug,
    Import,
    Stats,
    Pr,
    Github,
    Db,
    Upgrade,
    Uninstall,
    /// User-defined command from `.jankurai/commands/<id>.md`.
    UserDefined {
        id: String,
        body: String,
    },
    Unknown,
}

impl SlashAction {
    /// Map a built-in id to its action. Returns `Unknown` for ids that
    /// aren't in the static set.
    pub fn for_builtin_id(id: &str) -> Self {
        match id {
            "help" => Self::Help,
            "quit" => Self::Quit,
            "new" => Self::NewSession,
            "clear" => Self::Clear,
            "echo" => Self::Echo,
            "panels" => Self::Panels,
            "compact" => Self::Compact,
            "model" => Self::Model,
            "config" => Self::Config,
            "mcp" => Self::Mcp,
            "resume" => Self::Resume,
            "permissions" => Self::Permissions,
            "status" => Self::Status,
            "cost" => Self::Cost,
            "init" => Self::Init,
            "review" => Self::Review,
            "login" => Self::Login,
            "logout" => Self::Logout,
            "agents" => Self::Agents,
            "memory" => Self::Memory,
            "copy" => Self::Copy,
            "export" => Self::Export,
            "ps" => Self::Ps,
            "stop" => Self::Stop,
            "cd" => Self::Cd,
            "theme" => Self::Theme,
            "doctor" => Self::Doctor,
            "bug" => Self::Bug,
            "rename" => Self::Rename,
            "add-dir" => Self::AddDir,
            "vim" => Self::Vim,
            "jankurai" => Self::Jankurai,
            "audit" => Self::Audit,
            "audit-check" => Self::AuditCheck,
            "jankurai-status" => Self::JankuraiStatus,
            "score" => Self::Score,
            "sandbox" => Self::Sandbox,
            "keys" => Self::Keys,
            "daemon" => Self::Daemon,
            "plugin" => Self::Plugin,
            "features" => Self::Features,
            "session" => Self::Session,
            "fork" => Self::Fork,
            "attach" => Self::Attach,
            "serve" => Self::Serve,
            "run" => Self::Run,
            "completion" => Self::Completion,
            "providers" => Self::Providers,
            "models" => Self::Models,
            "acp" => Self::Acp,
            "mcp-server" => Self::McpServer,
            "debug" => Self::Debug,
            "import" => Self::Import,
            "stats" => Self::Stats,
            "pr" => Self::Pr,
            "github" => Self::Github,
            "db" => Self::Db,
            "upgrade" => Self::Upgrade,
            "uninstall" => Self::Uninstall,
            _ => Self::Unknown,
        }
    }

    pub fn for_id(id: &str) -> Self {
        Self::for_builtin_id(id)
    }
}
