use super::command::SlashCommand;

/// Full Claude/Codex parity built-in set. Order here is the popup display
/// order (commonly-used commands first, advanced/system commands later).
pub const BUILTIN_SLASH: &[SlashCommand] = &[
    SlashCommand::builtin("help", "show keyboard shortcuts and available commands"),
    SlashCommand::builtin(
        "new",
        "start a new session (pushes a divider into scrollback)",
    ),
    SlashCommand::builtin("clear", "push a divider into scrollback"),
    SlashCommand::builtin("compact", "compact the current conversation"),
    SlashCommand::builtin("model", "pick a model"),
    SlashCommand::builtin("config", "open the configuration editor"),
    SlashCommand::builtin("mcp", "browse Model Context Protocol servers"),
    SlashCommand::builtin("resume", "resume a previous session"),
    SlashCommand::builtin("permissions", "review and edit tool permissions"),
    SlashCommand::builtin("status", "show session status (tokens, model, cwd)"),
    SlashCommand::builtin("cost", "show token usage and estimated cost"),
    SlashCommand::builtin("init", "initialize CLAUDE.md / AGENTS.md in this repo"),
    SlashCommand::builtin("review", "review pending changes on the current branch"),
    SlashCommand::builtin("login", "log in to a provider"),
    SlashCommand::builtin("logout", "log out of the current provider"),
    SlashCommand::builtin("agents", "manage agent definitions"),
    SlashCommand::builtin("memory", "view or edit per-project memory"),
    SlashCommand::builtin("copy", "copy the last assistant response to the clipboard"),
    SlashCommand::builtin("export", "export the current transcript"),
    SlashCommand::builtin("ps", "list background processes spawned by tools"),
    SlashCommand::builtin("stop", "stop a background process by id"),
    SlashCommand::builtin("cd", "change the working directory for the session"),
    SlashCommand::builtin("theme", "pick a UI theme"),
    SlashCommand::builtin("doctor", "diagnose environment + provider health"),
    SlashCommand::builtin("bug", "file a bug report with session context"),
    SlashCommand::builtin("rename", "rename the current session"),
    SlashCommand::builtin("add-dir", "add another workspace directory"),
    SlashCommand::builtin("vim", "toggle Vim-style composer keybinds"),
    SlashCommand::builtin("echo", "toggle the echo backend"),
    SlashCommand::builtin("panels", "show classic panels"),
    SlashCommand::builtin("quit", "exit the inline chat surface"),
    SlashCommand::builtin("jankurai", "run a jankurai audit"),
    SlashCommand::builtin("audit", "alias for /jankurai"),
    SlashCommand::builtin("audit-check", "fast advisory-only audit (no ratchet)"),
    SlashCommand::builtin("jankurai-status", "show latest jankurai score"),
    SlashCommand::builtin("score", "alias for /jankurai-status"),
    SlashCommand::builtin("sandbox", "run a sandboxed shell command"),
    SlashCommand::builtin("keys", "manage API keys (lists sub-actions)"),
    SlashCommand::builtin("daemon", "background daemon control"),
    SlashCommand::builtin("plugin", "plugin management"),
    SlashCommand::builtin("features", "runtime feature flags"),
    SlashCommand::builtin("session", "session management"),
    SlashCommand::builtin("fork", "fork the current session"),
    SlashCommand::builtin("attach", "attach to a daemon session"),
    SlashCommand::builtin("serve", "start the HTTP server"),
    SlashCommand::builtin("run", "one-shot non-interactive run"),
    SlashCommand::builtin("completion", "print shell completion script"),
    SlashCommand::builtin("providers", "provider management"),
    SlashCommand::builtin("models", "model listing/picker"),
    SlashCommand::builtin("acp", "ACP integration"),
    SlashCommand::builtin("mcp-server", "run jekko as MCP server"),
    SlashCommand::builtin("debug", "diagnostic utilities"),
    SlashCommand::builtin("import", "import sessions"),
    SlashCommand::builtin("stats", "usage statistics"),
    SlashCommand::builtin("pr", "pull-request helpers"),
    SlashCommand::builtin("github", "GitHub event helpers"),
    SlashCommand::builtin("db", "database tools"),
    SlashCommand::builtin("upgrade", "upgrade jekko in place"),
    SlashCommand::builtin("uninstall", "uninstall jekko + data"),
];
