#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GlyphMode {
    Unicode,
    Ascii,
}

/// Static table of glyphs used across the jekko TUI.
#[derive(Debug, Clone, Copy)]
pub struct GlyphSet {
    pub bullet_success: &'static str,
    pub bullet_pending: &'static str,
    pub bullet_cancelled: &'static str,
    pub bullet_failed: &'static str,
    pub tree_branch: &'static str,
    pub composer_prefix: &'static str,
    pub divider: &'static str,
    pub ellipsis: &'static str,
    pub banner_prefix: &'static str,
    pub working_pulse: &'static str,
    pub card_margin: &'static str,
    pub boot_marker: &'static str,
    pub arrow_up: &'static str,
    pub arrow_down: &'static str,
    pub agent_done: &'static str,
    pub info_marker: &'static str,
    pub warning_marker: &'static str,
    pub error_marker: &'static str,
    pub running_bullet: &'static str,
    pub welcome_marker: &'static str,
    pub spinner_placeholder: &'static str,
    pub cursor_block: &'static str,
    pub separator_dot: &'static str,
}

pub const UNICODE: GlyphSet = GlyphSet {
    bullet_success: "●",
    bullet_pending: "○",
    bullet_cancelled: "◌",
    bullet_failed: "×",
    tree_branch: "└",
    composer_prefix: "›",
    divider: "─",
    ellipsis: "…",
    banner_prefix: "▸▸",
    working_pulse: "◦",
    card_margin: "│",
    boot_marker: "⚡",
    arrow_up: "↑",
    arrow_down: "↓",
    agent_done: "✓",
    info_marker: "ⓘ",
    warning_marker: "▲",
    error_marker: "✕",
    running_bullet: "◉",
    welcome_marker: "✻",
    spinner_placeholder: "⋯",
    cursor_block: "█",
    separator_dot: "·",
};

pub const ASCII: GlyphSet = GlyphSet {
    bullet_success: "*",
    bullet_pending: "o",
    bullet_cancelled: ".",
    bullet_failed: "x",
    tree_branch: "\\",
    composer_prefix: ">",
    divider: "-",
    ellipsis: "...",
    banner_prefix: ">>",
    working_pulse: "o",
    card_margin: "|",
    boot_marker: "!",
    arrow_up: "^",
    arrow_down: "v",
    agent_done: "[v]",
    info_marker: "(i)",
    warning_marker: "!",
    error_marker: "x",
    running_bullet: "o",
    welcome_marker: "*",
    spinner_placeholder: "...",
    cursor_block: "#",
    separator_dot: "-",
};
