export const RECOMMENDED_MODELS: Record<string, string> = {
  openai: "gpt-5.3-codex",
  anthropic: "claude-sonnet-4-5",
  google: "gemini-2.5-flash",
  openrouter: "openrouter-gpt-oss-120b-free",
  groq: "groq-qwen3-32b",
  cerebras: "cerebras-qwen-3-235b-a22b-instruct-2507",
  mistral: "mistral-devstral-latest",
  github: "github-codestral-2501",
  nvidia: "nvidia-deepseek-v4-pro",
  fireworks: "fireworks-deepseek-v4-pro",
  dashscope: "alibaba-qwen3-coder-plus",
  sambanova: "sambanova-gpt-oss-120b",
  huggingface: "huggingface-qwen3-coder-next",
  zai: "zai-glm-47-flash",
  inception: "inception-mercury-2",
  "ai-gateway": "vercel-claude-sonnet-46",
  kilo: "kilo-ling-26-1t-free",
  cloudflare: "cloudflare-gpt-oss-120b",
  jekko: "big-pickle",
}
